export const titlePresets = [
  {
    id: 'lower-third-1',
    name: 'Classic Lower Third',
    content: 'JOHN DOE\nCreative Director',
    font: 'Archivo',
    size: 32,
    color: '#ffffff',
    align: 'left',
    background: 'rgba(20, 21, 24, 0.85)',
    bgRadius: 8,
    paddingX: 24,
    paddingY: 16,
    maxWidth: 600,
    animations: { in: 'slide', inDuration: 0.5, out: 'fade', outDuration: 0.3 }
  },
  {
    id: 'headline-center',
    name: 'Centered Headline',
    content: 'MAIN TITLE',
    font: 'Archivo',
    size: 72,
    color: '#F59E2D',
    align: 'center',
    shadow: { color: 'rgba(0,0,0,0.8)', blur: 15, offsetX: 0, offsetY: 4 },
    animations: { in: 'pop', inDuration: 0.4, out: 'fade', outDuration: 0.4 }
  },
  {
    id: 'kinetic-caption',
    name: 'Kinetic Caption',
    content: 'Watch this space...',
    font: 'Archivo',
    size: 48,
    color: '#ECEAE6',
    align: 'center',
    background: '#F59E2D',
    bgRadius: 4,
    paddingX: 16,
    paddingY: 8,
    animations: { in: 'typewriter', inDuration: 1.5, out: 'slide', outDuration: 0.5 }
  },
  {
    id: 'end-credits',
    name: 'End Credits',
    content: 'DIRECTED BY\nJane Smith\n\nPRODUCED BY\nClipForge Studios',
    font: 'Archivo',
    size: 24,
    color: '#A0A5AD',
    align: 'center',
    animations: { in: 'fade', inDuration: 1.0, out: 'fade', outDuration: 1.0 }
  },
  {
    id: 'social-tag',
    name: 'Social Handle',
    content: '@clipforge_app',
    font: 'Archivo',
    size: 28,
    color: '#ffffff',
    align: 'left',
    background: '#1C1E22',
    bgRadius: 20,
    paddingX: 20,
    paddingY: 10,
    stroke: '#F59E2D',
    strokeWidth: 1,
    animations: { in: 'slide', inDuration: 0.3, out: 'slide', outDuration: 0.3 }
  },
  {
    id: 'meme-text',
    name: 'Meme Text',
    content: 'WHEN YOU REALIZE',
    font: 'Impact, sans-serif',
    size: 64,
    color: '#ffffff',
    align: 'center',
    stroke: '#000000',
    strokeWidth: 4,
    shadow: { color: '#000000', blur: 0, offsetX: 2, offsetY: 2 },
    animations: { in: 'pop', inDuration: 0.2 }
  },
  {
    id: 'news-ticker',
    name: 'News Ticker',
    content: 'BREAKING NEWS: New Features Arrive',
    font: 'Archivo',
    size: 24,
    color: '#141518',
    align: 'left',
    background: '#ffffff',
    paddingX: 1000,
    paddingY: 8,
    animations: { in: 'slide', inDuration: 0.5, out: 'slide', outDuration: 0.5 }
  },
  {
    id: 'neon-sign',
    name: 'Amber Glow',
    content: 'LATE NIGHT',
    font: 'Archivo',
    size: 80,
    color: '#ffffff',
    align: 'center',
    shadow: { color: '#F59E2D', blur: 20, offsetX: 0, offsetY: 0 },
    animations: { in: 'fade', inDuration: 1.0 }
  },
  {
    id: 'typewriter-minimal',
    name: 'Minimal Type',
    content: 'Chapter 1: The Beginning',
    font: 'Courier New, monospace',
    size: 36,
    color: '#ECEAE6',
    align: 'center',
    animations: { in: 'typewriter', inDuration: 2.0, out: 'fade', outDuration: 1.0 }
  },
  {
    id: 'quote-block',
    name: 'Quote Block',
    content: '"Creativity is intelligence having fun."\n- Albert Einstein',
    font: 'Georgia, serif',
    size: 32,
    color: '#ECEAE6',
    align: 'center',
    background: 'rgba(38, 41, 46, 0.9)',
    bgRadius: 12,
    paddingX: 40,
    paddingY: 30,
    stroke: '#555A64',
    strokeWidth: 1,
    animations: { in: 'fade', inDuration: 0.8, out: 'fade', outDuration: 0.8 }
  },
  {
    id: 'alert-banner',
    name: 'Alert Banner',
    content: 'WARNING',
    font: 'Archivo',
    size: 48,
    color: '#000000',
    align: 'center',
    background: '#F59E2D',
    paddingX: 200,
    paddingY: 10,
    animations: { in: 'pop', inDuration: 0.3, out: 'slide', outDuration: 0.3 }
  },
  {
    id: 'vlog-intro',
    name: 'Vlog Intro',
    content: 'A DAY IN THE LIFE',
    font: 'Archivo',
    size: 56,
    color: '#ffffff',
    align: 'center',
    stroke: '#F59E2D',
    strokeWidth: 2,
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 10, offsetX: 4, offsetY: 4 },
    animations: { in: 'slide', inDuration: 0.6, out: 'fade', outDuration: 0.4 }
  }
];